config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'menus#index'
  resources :menus
    scope module: :menus do
      resources :add_to_carts, only:[:create]
      resources :delete_in_carts, only:[:create]
    end

  resource :cart, only:[:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :menu, through: :cart_menus
  has_many :cart_menus, dependent: :destroy
end

app/models/cart_menu.rb
class CartMenu < ApplicationRecord
  belongs_to :menu
  belongs_to :cart
end

app/models/menu.rb
class Menu < ApplicationRecord
  with_options presence: true do
    validates :product_name
    validates :product_description
    validates :product_category_id
    validates :price
  end

  validates :product_category_id, numericality: { other_than: 1, message: 'is invalid.' }

  belongs_to :user
  has_many :cart_menus, dependent: :destroy
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :product_category
end

app/models/product_category.rb
class ProductCategory < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '前菜' },
    { id: 3, name: 'アラカルト' },
    { id: 4, name: 'パスタ' },
    { id: 5, name: 'メインディッシュ' },
    { id: 6, name: 'デザート' },
    { id: 7, name: 'ノンアルドリンク' },
    { id: 8, name: 'ワイン' }
  ]

  include ActiveHash::Associations
  has_many :menus
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  with_options presence: true do
    validates :nickname
    validates :password
    validates :password_confirmation
  end

  validates :password, length: { minimum: 6 }
  validates :password, confirmation: true

  has_many :menus
  has_one :cart, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :password])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_menu, except: [:index, :new, :create]
  before_action :move_to_root_path, only: [:new, :edit, :destroy]

  def index
    @menu = Menu.all
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @menu.update(menu_params)
      render :show
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @menu.destroy
  end

  private

  def menu_params
    params.require(:menu).permit(:image, :product_name, :product_description, :product_category_id,
                                 :price).merge(user_id: current_user.id)
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end

  # 管理者以外出品・編集・削除不可にする
  def move_to_root_path
    redirect_to root_path if current_user.id != 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav-left">
            <%= link_to image_tag("IMG_0555.jpg", class: :logo), root_path %>
          </div>
          <div class="nav-right">
          <% if user_signed_in? %>
            <%= link_to "#{current_user.nickname}さん", new_user_session_path , class: :nav_btn %>
            <%= link_to "ログアウト", destroy_user_session_path, class: :nav_btn, method: :delete %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path , class: :nav_btn %>
            <%= link_to "新規登録", new_user_registration_path, class: :nav_btn %>
          <% end %>
          </div>
        </div>
      </div>
    </header>
      <%= yield %>
    <footer class="text-muted py-5 bg-danger">
      <div class="container text-dark">
        <p class="mb-1 text-center lead">©️ Trattoria Salice by Yanagi Group</p>
      </div>
    </footer>
  </body>
</html>

app/views/menus/_form.edit.html.erb
<%# 料理入力欄 %>

<%= form_with model: @menu, url: menu_path, local: true do |f| %>

  <div class="field">
    <%= f.label :image, "料理画像" %><br />
    <%= f.file_field :image, id:"menu_image" %>
  </div>

  <div class="field">
    <%= f.label :product_name, "料理名" %><br />
    <%= f.text_field :product_name, id:"menu_name" %>
  </div>

  <div class="field">
    <%= f.label :product_description, "料理説明" %><br />
    <%= f.text_area :product_description, class: :form__text, id:"menu_product_description" %>
  </div>

  <div class="field">
    <%= f.label :product_category_id, "カテゴリー" %><br />
    <%= f.collection_select(:product_category_id, ProductCategory.all, :id, :name, {}, {class:"select-box", id:"nemu_product_category"}) %>
  </div>

    <div class="field">
    <%= f.label :price, "値段" %><br />
    <%= f.text_field :price, id:"menu_price" %> 円
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn %>
  </div>
<% end %>

<%# /料理入力欄  %>

app/views/menus/_form.html.erb
<%# 料理入力欄 %>

<%= form_with model: @menu, url: menus_path, local: true do |f| %>

  <div class="field">
    <%= f.label :image, "料理画像" %><br />
    <%= f.file_field :image, id:"menu_image" %>
  </div>

  <div class="field">
    <%= f.label :product_name, "料理名" %><br />
    <%= f.text_field :product_name, id:"menu_name" %>
  </div>

  <div class="field">
    <%= f.label :product_description, "料理説明" %><br />
    <%= f.text_area :product_description, class: :form__text, id:"menu_product_description" %>
  </div>

  <div class="field">
    <%= f.label :product_category_id, "カテゴリー" %><br />
    <%= f.collection_select(:product_category_id, ProductCategory.all, :id, :name, {}, {class:"select-box", id:"nemu_product_category"}) %>
  </div>

    <div class="field">
    <%= f.label :price, "値段" %><br />
    <%= f.text_field :price, id:"menu_price" %> 円
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn %>
  </div>
<% end %>

<%# /料理入力欄  %>

app/views/menus/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">メニュー入力欄</h2>
        <%= render partial: "form.edit", locals: { menu: @menu } %>
    </div>
  </div>
</div>

app/views/menus/index.html.erb
<html lang="ja"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>アルバムサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>

<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Buona Sera!!</h1>
        <p class="lead text-muted">ようこそ Trattoria Saliceへ</p>
        <%#p>現段階では表示しない。イベント告知等に使用予定
          <a href="#" class="btn btn-primary my-2">メインアクション</a>
          <a href="#" class="btn btn-secondary my-2">サブアクション</a>
        <%/p%>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @menu.each do |menu| %>
        <div class="col">
          <div class="card shadow-sm">
            <%= image_tag(menu.image, class:"bd-placeholder-img card-img-top", width:"100%", height:"300", preserveAspectRatio:"xMidYMid slice") %>

            <div class="card-body">
              <p class="card-text">
                <%= menu.product_description %>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to "料理の詳細を見る", menu_path(menu.id), class: 'btn btn-sm btn-outline-secondary' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>

</main>

</body></html>

app/views/menus/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">メニュー入力欄</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { menu: @menu } %>
    </div>
  </div>
</div>

app/views/menus/show.html.erb
<main class="main">
  <div class="inner">
    <div class="menu__wrapper">
      <div class="menu__hedding">
        <%= @menu.product_name %>
      </div>
      <div class="pb-5 mt-2 mb-5 menu__content">
        <div class="menu__image">
          <%= image_tag(@menu.image, width:"400", height:"300") %>
        </div>
        <div class="menu__detail">
          <p class="detail__title">商品説明</p>
          <p class="detail__message">
            <%= @menu.product_description %>
          </p>
        </div>
        <div class="menu__detail">
          <p class="detail__title">カテゴリー</p>
          <p class="detail__message">
            <%= @menu.product_category.name %>
          </p>
        </div>
        <div class="menu__detail">
          <p class="detail__title">料金</p>
          <p class="detail__message">
            ¥ <%= @menu.price %>
          </p>
        </div>
        <div class="menu__detail">
          <p class="detail__title">
            <% if user_signed_in? && current_user != @menu.user %>
              <%= link_to "購入画面に進む","#", class:"item-btn" %>
            <% else %>
              <%= link_to "商品情報を編集する", edit_menu_path(@menu), method: :get, class:"item-btn" %>
              <%= link_to "商品情報を削除する", menu_path(@menu), method: :delete, class:"item-btn" %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</main>